services: 
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: workflow_db
    ports:
      - "5432:5432"
    
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
  
